// Colour themes. `vars` are applied as CSS custom properties on <html>.
export const THEMES = [
  {
    key: "gold",
    name: "Royal Gold",
    swatch: ["#b8872d", "#171717", "#f7ecd1"],
    vars: {
      "--gold": "#b8872d",
      "--gold-dark": "#9a7026",
      "--gold2": "#c79a3d",
      "--champ": "#f7ecd1",
      "--cream": "#fbf8f1",
      "--accent": "#c79a3d",
      "--sidebar-bg": "#171717",
      "--sidebar-hover": "#29261f",
      "--sidebar-logo": "#f0cb78",
      "--sidebar-text": "#e2ddd3",
      "--sidebar-muted": "#a09a8e",
      "--avatar-bg": "#d7b15c",
      "--avatar-text": "#171717",
      "--bg": "#f2eee5",
      "--shell": "#f5f3ee",
      "--ink": "#171717",
      "--soft": "#6f6a61",
      "--line": "#e8dfcf",
      "--line-soft": "#eee8dc",
      "--topbar-line": "#eee5d5",
      "--th-text": "#8b867d",
    },
  },
  {
    key: "blue",
    name: "Corporate Blue",
    swatch: ["#2563eb", "#0f172a", "#dbeafe"],
    vars: {
      "--gold": "#2563eb",
      "--gold-dark": "#1d4ed8",
      "--gold2": "#3b82f6",
      "--champ": "#dbeafe",
      "--cream": "#f3f7ff",
      "--accent": "#3b82f6",
      "--sidebar-bg": "#0f172a",
      "--sidebar-hover": "#1e293b",
      "--sidebar-logo": "#93c5fd",
      "--sidebar-text": "#e2e8f0",
      "--sidebar-muted": "#94a3b8",
      "--avatar-bg": "#60a5fa",
      "--avatar-text": "#0f172a",
      "--bg": "#eef2f9",
      "--shell": "#f1f5fb",
      "--ink": "#0f172a",
      "--soft": "#5b6b83",
      "--line": "#dbe4f0",
      "--line-soft": "#e8eef7",
      "--topbar-line": "#e2e9f4",
      "--th-text": "#7c8aa3",
    },
  },
  {
    key: "emerald",
    name: "Emerald Green",
    swatch: ["#0f7b5f", "#0b2b23", "#d3f0e4"],
    vars: {
      "--gold": "#0f7b5f",
      "--gold-dark": "#0b6350",
      "--gold2": "#159e78",
      "--champ": "#d3f0e4",
      "--cream": "#f0f9f5",
      "--accent": "#159e78",
      "--sidebar-bg": "#0b2b23",
      "--sidebar-hover": "#123f34",
      "--sidebar-logo": "#6ee7b7",
      "--sidebar-text": "#dcefe7",
      "--sidebar-muted": "#8fb5a7",
      "--avatar-bg": "#34d399",
      "--avatar-text": "#06231c",
      "--bg": "#eaf5f0",
      "--shell": "#eef7f2",
      "--ink": "#10241d",
      "--soft": "#587a6f",
      "--line": "#d6e8e0",
      "--line-soft": "#e6f2ec",
      "--topbar-line": "#ddeee7",
      "--th-text": "#6f8f84",
    },
  },
  {
    key: "maroon",
    name: "Maroon Red",
    swatch: ["#9b1c31", "#2a0d13", "#f7d9de"],
    vars: {
      "--gold": "#9b1c31",
      "--gold-dark": "#7f1528",
      "--gold2": "#b8304a",
      "--champ": "#f7d9de",
      "--cream": "#fdf1f3",
      "--accent": "#b8304a",
      "--sidebar-bg": "#2a0d13",
      "--sidebar-hover": "#43151d",
      "--sidebar-logo": "#f3aab8",
      "--sidebar-text": "#f0dfe2",
      "--sidebar-muted": "#b9949b",
      "--avatar-bg": "#e07a8f",
      "--avatar-text": "#2a0d13",
      "--bg": "#f7eef0",
      "--shell": "#f9f2f4",
      "--ink": "#2a0d13",
      "--soft": "#7c5a61",
      "--line": "#ecd6da",
      "--line-soft": "#f4e6e9",
      "--topbar-line": "#f0dfe3",
      "--th-text": "#96727a",
    },
  },
  {
    key: "violet",
    name: "Royal Violet",
    swatch: ["#6d28d9", "#1e1033", "#e4dbfb"],
    vars: {
      "--gold": "#6d28d9",
      "--gold-dark": "#5b21b6",
      "--gold2": "#7c3aed",
      "--champ": "#e4dbfb",
      "--cream": "#f5f1fe",
      "--accent": "#7c3aed",
      "--sidebar-bg": "#1e1033",
      "--sidebar-hover": "#2e1a4d",
      "--sidebar-logo": "#c4b5fd",
      "--sidebar-text": "#e6dff5",
      "--sidebar-muted": "#a294c2",
      "--avatar-bg": "#a78bfa",
      "--avatar-text": "#1e1033",
      "--bg": "#f3f0fb",
      "--shell": "#f5f2fc",
      "--ink": "#1e1033",
      "--soft": "#6b6285",
      "--line": "#e2d9f5",
      "--line-soft": "#ede7fa",
      "--topbar-line": "#e6def7",
      "--th-text": "#837aa0",
    },
  },
  {
    key: "slate",
    name: "Slate Grey",
    swatch: ["#334155", "#0b1220", "#e2e8f0"],
    vars: {
      "--gold": "#334155",
      "--gold-dark": "#1e293b",
      "--gold2": "#475569",
      "--champ": "#e2e8f0",
      "--cream": "#f6f8fa",
      "--accent": "#475569",
      "--sidebar-bg": "#0b1220",
      "--sidebar-hover": "#1b2637",
      "--sidebar-logo": "#cbd5e1",
      "--sidebar-text": "#e2e8f0",
      "--sidebar-muted": "#8b98ac",
      "--avatar-bg": "#94a3b8",
      "--avatar-text": "#0b1220",
      "--bg": "#eef1f5",
      "--shell": "#f1f4f8",
      "--ink": "#0f172a",
      "--soft": "#5b6b7f",
      "--line": "#dbe2ea",
      "--line-soft": "#e8edf3",
      "--topbar-line": "#e1e8f0",
      "--th-text": "#7c8aa0",
    },
  },
];

export const COUNTRY_CODES = [
  { code: "+91", label: "India (+91)" },
  { code: "+1", label: "USA / Canada (+1)" },
  { code: "+44", label: "United Kingdom (+44)" },
  { code: "+971", label: "UAE (+971)" },
  { code: "+966", label: "Saudi Arabia (+966)" },
  { code: "+974", label: "Qatar (+974)" },
  { code: "+965", label: "Kuwait (+965)" },
  { code: "+973", label: "Bahrain (+973)" },
  { code: "+968", label: "Oman (+968)" },
  { code: "+92", label: "Pakistan (+92)" },
  { code: "+880", label: "Bangladesh (+880)" },
  { code: "+977", label: "Nepal (+977)" },
  { code: "+94", label: "Sri Lanka (+94)" },
  { code: "+975", label: "Bhutan (+975)" },
  { code: "+960", label: "Maldives (+960)" },
  { code: "+61", label: "Australia (+61)" },
  { code: "+64", label: "New Zealand (+64)" },
  { code: "+65", label: "Singapore (+65)" },
  { code: "+60", label: "Malaysia (+60)" },
  { code: "+62", label: "Indonesia (+62)" },
  { code: "+66", label: "Thailand (+66)" },
  { code: "+84", label: "Vietnam (+84)" },
  { code: "+63", label: "Philippines (+63)" },
  { code: "+81", label: "Japan (+81)" },
  { code: "+82", label: "South Korea (+82)" },
  { code: "+86", label: "China (+86)" },
  { code: "+852", label: "Hong Kong (+852)" },
  { code: "+27", label: "South Africa (+27)" },
  { code: "+234", label: "Nigeria (+234)" },
  { code: "+254", label: "Kenya (+254)" },
  { code: "+20", label: "Egypt (+20)" },
  { code: "+49", label: "Germany (+49)" },
  { code: "+33", label: "France (+33)" },
  { code: "+39", label: "Italy (+39)" },
  { code: "+34", label: "Spain (+34)" },
  { code: "+31", label: "Netherlands (+31)" },
  { code: "+32", label: "Belgium (+32)" },
  { code: "+41", label: "Switzerland (+41)" },
  { code: "+43", label: "Austria (+43)" },
  { code: "+46", label: "Sweden (+46)" },
  { code: "+47", label: "Norway (+47)" },
  { code: "+45", label: "Denmark (+45)" },
  { code: "+48", label: "Poland (+48)" },
  { code: "+351", label: "Portugal (+351)" },
  { code: "+353", label: "Ireland (+353)" },
  { code: "+30", label: "Greece (+30)" },
  { code: "+90", label: "Turkey (+90)" },
  { code: "+7", label: "Russia (+7)" },
  { code: "+380", label: "Ukraine (+380)" },
  { code: "+55", label: "Brazil (+55)" },
  { code: "+52", label: "Mexico (+52)" },
  { code: "+54", label: "Argentina (+54)" },
  { code: "+56", label: "Chile (+56)" },
  { code: "+57", label: "Colombia (+57)" },
  { code: "+51", label: "Peru (+51)" },
  { code: "+593", label: "Ecuador (+593)" },
  { code: "+972", label: "Israel (+972)" },
  { code: "+98", label: "Iran (+98)" },
  { code: "+964", label: "Iraq (+964)" },
  { code: "+962", label: "Jordan (+962)" },
  { code: "+961", label: "Lebanon (+961)" },
  { code: "+93", label: "Afghanistan (+93)" },
  { code: "+95", label: "Myanmar (+95)" },
  { code: "+855", label: "Cambodia (+855)" },
  { code: "+856", label: "Laos (+856)" },
  { code: "+673", label: "Brunei (+673)" },
  { code: "+676", label: "Tonga (+676)" },
  { code: "+679", label: "Fiji (+679)" },
];

export const TIMEZONES = [
  { value: -480, label: "UTC-08:00 (Los Angeles)" },
  { value: -300, label: "UTC-05:00 (New York)" },
  { value: -180, label: "UTC-03:00 (Sao Paulo)" },
  { value: 0, label: "UTC+00:00 (London)" },
  { value: 60, label: "UTC+01:00 (Paris)" },
  { value: 120, label: "UTC+02:00 (Cairo)" },
  { value: 180, label: "UTC+03:00 (Moscow)" },
  { value: 210, label: "UTC+03:30 (Tehran)" },
  { value: 240, label: "UTC+04:00 (Dubai)" },
  { value: 270, label: "UTC+04:30 (Kabul)" },
  { value: 300, label: "UTC+05:00 (Karachi)" },
  { value: 330, label: "UTC+05:30 (India - IST)" },
  { value: 345, label: "UTC+05:45 (Kathmandu)" },
  { value: 360, label: "UTC+06:00 (Dhaka)" },
  { value: 390, label: "UTC+06:30 (Yangon)" },
  { value: 420, label: "UTC+07:00 (Bangkok)" },
  { value: 480, label: "UTC+08:00 (Singapore)" },
  { value: 540, label: "UTC+09:00 (Tokyo)" },
  { value: 570, label: "UTC+09:30 (Adelaide)" },
  { value: 600, label: "UTC+10:00 (Sydney)" },
  { value: 720, label: "UTC+12:00 (Auckland)" },
];

// 30-minute steps for the send window
export const TIME_OPTIONS = (() => {
  const out = [];
  for (let h = 0; h < 24; h += 1) {
    for (let m = 0; m < 60; m += 30) {
      const hh = String(h).padStart(2, "0");
      const mm = String(m).padStart(2, "0");
      out.push({ value: `${hh}:${mm}`, label: `${hh}:${mm}` });
    }
  }
  return out;
})();

export const TEMPLATE_CATEGORIES = [
  { value: "general", label: "General" },
  { value: "marketing", label: "Marketing" },
  { value: "promotional", label: "Promotional" },
  { value: "transactional", label: "Transactional" },
  { value: "utility", label: "Utility" },
  { value: "authentication", label: "Authentication" },
  { value: "announcement", label: "Announcement" },
  { value: "reminder", label: "Reminder" },
];

export const WA_LANGUAGES = [
  { value: "en", label: "English (en)" },
  { value: "en_US", label: "English US (en_US)" },
  { value: "en_GB", label: "English UK (en_GB)" },
  { value: "hi", label: "Hindi (hi)" },
  { value: "gu", label: "Gujarati (gu)" },
  { value: "mr", label: "Marathi (mr)" },
  { value: "bn", label: "Bengali (bn)" },
  { value: "ta", label: "Tamil (ta)" },
  { value: "te", label: "Telugu (te)" },
  { value: "kn", label: "Kannada (kn)" },
  { value: "ml", label: "Malayalam (ml)" },
  { value: "pa", label: "Punjabi (pa)" },
  { value: "ur", label: "Urdu (ur)" },
  { value: "ar", label: "Arabic (ar)" },
  { value: "es", label: "Spanish (es)" },
  { value: "fr", label: "French (fr)" },
  { value: "de", label: "German (de)" },
  { value: "pt_BR", label: "Portuguese BR (pt_BR)" },
];

export const META_API_VERSIONS = [
  { value: "v21.0", label: "v21.0" },
  { value: "v20.0", label: "v20.0" },
  { value: "v19.0", label: "v19.0" },
  { value: "v18.0", label: "v18.0" },
  { value: "v17.0", label: "v17.0" },
];

export const MSG91_ROUTES = [
  { value: "4", label: "Transactional (4)" },
  { value: "1", label: "Promotional (1)" },
  { value: "2", label: "OTP (2)" },
];

export const FAST2SMS_ROUTES = [
  { value: "q", label: "Quick (q)" },
  { value: "d", label: "DLT / Documented (d)" },
  { value: "t", label: "Transactional (t)" },
  { value: "o", label: "OTP (o)" },
];

export const FAST2SMS_LANGUAGES = [
  { value: "english", label: "English" },
  { value: "unicode", label: "Unicode" },
];
